name: Docker Image CI

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'
jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/mlflow-spam
          tags: |
            type=edge,branch=master
            type=sha,enable=true,prefix=git-,format=short
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./train_model
          target: model-build
          cache-to: |
            type=gha,mode=max,scope=${{ github.repository }}
          cache-from: |
            type=gha,scope=${{ github.repository }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      -
        name: Docker meta
        id: meta-model
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/model-spam
          tags: |
            type=edge,branch=master
            type=sha,enable=true,prefix=git-,format=short
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
      -
        name: Build and push (model)
        uses: docker/build-push-action@v4
        with:
          context: ./train_model
          target: model
          cache-to: |
            type=gha,mode=max,scope=${{ github.repository }}
          cache-from: |
            type=gha,scope=${{ github.repository }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-model.outputs.tags }}
          labels: ${{ steps.meta-model.outputs.labels }}
    